-- MySQL Script generated by MySQL Workbench
-- Sun Apr 13 18:33:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PersonalClean
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PersonalClean
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PersonalClean` DEFAULT CHARACTER SET utf8 ;
USE `PersonalClean` ;

-- -----------------------------------------------------
-- Table `PersonalClean`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `f_nacimiento` DATE NOT NULL,
  `descripcion` VARCHAR(1000) NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `notaMedia` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idfuncionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalClean`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `f_nacimiento` VARCHAR(45) NOT NULL,
  `foto_perfil` VARCHAR(255) NULL,
  `notaMedia` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalClean`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`servicios` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `idcliente` INT NOT NULL,
  `idFuncionario` INT NULL,
  `fechaServicio` DATE NOT NULL,
  `estado` ENUM('activo', 'terminado', 'confirmacion') NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(2000) NOT NULL,
  `tipoServicio` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `diaServicio` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idServicio`),
  CONSTRAINT `idFuncionariServicio`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `PersonalClean`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idClienteServicio`
    FOREIGN KEY (`idcliente`)
    REFERENCES `PersonalClean`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `PersonalClean`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`chats` (
  `idchats` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idchats`),
  CONSTRAINT `idFuncionariChat`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `PersonalClean`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idClienteChat`
    FOREIGN KEY (`idCliente`)
    REFERENCES `PersonalClean`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalClean`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`mensajes` (
  `idmensajes` INT NOT NULL AUTO_INCREMENT,
  `idChat` INT NOT NULL,
  `contenido` VARCHAR(1000) NOT NULL,
  `envia` INT NOT NULL,
  `fechaHora` TIMESTAMP NOT NULL,
  `visto` ENUM('si', 'no') NOT NULL,
  PRIMARY KEY (`idmensajes`),
  CONSTRAINT `fk_idChat_mensajes`
    FOREIGN KEY (`idChat`)
    REFERENCES `PersonalClean`.`chats` (`idchats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `PersonalClean`.`valoraciones_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`valoraciones_Cliente` (
  `idvaloraciones` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `estrellas` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idvaloraciones`),
  CONSTRAINT `idFuncionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `PersonalClean`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `PersonalClean`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalClean`.`valoraciones_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`valoraciones_servicios` (
  `idvaloraciones_servicios` INT NOT NULL AUTO_INCREMENT,
  `idServicio` INT NOT NULL,
  `estrella` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idvaloraciones_servicios`),
  CONSTRAINT `fk_val_serv_idServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `PersonalClean`.`servicios` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_val_serv_idFuncionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `PersonalClean`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalClean`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`administradores` (
  `idadministradores` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministradores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PersonalClean`.`pedidoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PersonalClean`.`pedidoServicio` (
  `idpedidoServicio` INT NOT NULL AUTO_INCREMENT,
  `idServicio` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `activo` ENUM('si', 'no') NOT NULL,
  `descripcion` VARCHAR(1000) NULL,
  `valorAlternativo` DECIMAL(5,2) NULL,
  `diaServicioAlternativo` VARCHAR(45) NULL,
  PRIMARY KEY (`idpedidoServicio`),
  CONSTRAINT `fk_pedidoservicio_idServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `PersonalClean`.`servicios` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoservicio_idFuncionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `PersonalClean`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
